[theme]
name = "catppuccin-macchiato-blue"

[colors]
AlertInfo = "#a6da95"
AlertWarn = "#f5a97f"
AlertError = "#ed8796"
Annotation = "#8aadf4"
Base = "#cad3f5"
Guidance = "#939ab7"
Important = "#ed8796"
Title = "#8aadf4" 