[theme]
name = "catppuccin-macchiato-mauve"

[colors]
AlertInfo = "#a6da95"
AlertWarn = "#f5a97f"
AlertError = "#ed8796"
Annotation = "#c6a0f6"
Base = "#cad3f5"
Guidance = "#939ab7"
Important = "#ed8796"
Title = "#c6a0f6" 