[theme]
name = "catppuccin-macchiato-pink"

[colors]
AlertInfo = "#a6da95"
AlertWarn = "#f5a97f"
AlertError = "#ed8796"
Annotation = "#f5bde6"
Base = "#cad3f5"
Guidance = "#939ab7"
Important = "#ed8796"
Title = "#f5bde6" 